### ISSUE TITLE
macOS Mojave (10.14) - Compatibility Report (UX330UAR)

### ISSUE THREAD

**Issue by AwlsomeAlex** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#8] opened 2018-09-19 22:58 UTC
ASUS ZenBook UX330UAR (UX330UA-AH55)

macOS Version: macOS Mojave Beta 11 (GM?)

Intel Core i5-8250U
8GB RAM / Intel UHD Graphics 620
256GB Micron PCIe SATA

With macOS Mojave (10.14) days away from release, I think it's time to start experimenting as to what laptops work out-of-the-box, what kexts need to be fixed, or what else needs to be patched. As I wait for a Wi-Fi Card to come in (My USB Wi-Fi was borrowed) I will experiment with my UX330UAR and report back here what's the deal with macOS Mojave Beta 11 (Maybe the GM, who knows at this point.)

**Comment by AwlsomeAlex** [comment] 2018-09-20 01:53
###### Last Updated: 9/19/18 10:33pm
# First Impressions:
## Installer
### What works:
* Everything you'd expect +
* Battery Indicator, FN Keys (16 Levels) and Brightness
### What doesn't work:
* ~~3D Acceleration: Screen shows weird color variations/weird graphics [Lilu/WhateverGreen or DSDT Patch?]~~
* Trackpad (Expected not to work in Installer)
### What MIGHT not work:
* [Read about something](https://hackintosher.com/guides/updating-your-hackintosh-to-mojave-10-14/) with a USB Patch needed to get full functionality. 
### NOTES:
* Installed with APFS Formatted Drive (Used APFS.efi right from Mac Pro) due to rumors of Mojave not updating when installed on HFS+ Drives (Explains why my Mac Pro never updates....).

## Welcome Screen
* No Changes, Including Trackpad not working....

## Desktop
I was mistaken, there is 3D Acceleration, however, the font seems a bit blurry.
* Trackpad is NOT functional

## Fixing Graphics:
~~If the graphics remain to be weird beyond install, until the XNU Source Code is released and projects such as WhateverGreen and Lilu get time to upgrade, I'll try a hacked kext provided by dosdude1 to fix graphics acceleration. (Not sure why it isn't working natively in the first place.)~~
The font seems to be a bit blurry. I'll try the following regardless to see if it helps.
~~[Found something](https://hackintosher.com/guides/updating-your-hackintosh-to-mojave-10-14/) saying to boot with `-igfxbeta` will try this.~~
Font Smoothing was disabled. Use this command and log out and back in to fix it:
`defaults -currentHost write -globalDomain AppleFontSmoothing -int 1`

**Comment by AwlsomeAlex** [comment] 2018-09-20 02:26
###### Last Updated: 9/19/18 11:17pm
# Current Issues:
* No Trackpad Support [Possibly VoodooI2C is waiting for XNU Source Code release]
* ~~Graphics/Font seems a bit blurry [Unknown]~~ [Fixed](https://www.howtogeek.com/358596/how-to-fix-blurry-fonts-on-macos-mojave-with-subpixel-antialiasing/) 
* **FATAL ISSUE:** After installing kexts through the `./install.sh` command macOS Mojave won't even boot anymore.... :/ **Tried F2 to get Preboot for gen_debug and now NOTHING boots...... Time for square 1.** Can you put in some input?

**Comment by hieplpvip** [comment] 2018-09-20 04:33
Important rule for testing: never install kexts to /L/E

Kernel panic is probably caused by VoodooI2C. Your only choice now is to reinstall macOS.

P/s: how many levels for keyboard backlight?

**Comment by AwlsomeAlex** [comment] 2018-09-20 05:01
I didn’t see specifically how many levels but I know for certain it was more than 3, also I didn’t install to /L/E for that specific reason, and it can’t be by VoodooI2C otherwise the Installer wouldn’t have even booted. My guess is either the injector, the CPU Mod, or one of the three kexts that can’t be installed to Clover. 

I must note something odd was in Verbose debug it got to as far as 
`Thunderbolt Bus:` before crashing. 
I’ll keep trying, but it will be a little slow until my USB Wi-Fi card comes in, since that’ll speed up the process a little bit.

**Comment by hieplpvip** [comment] 2018-09-20 13:03
None of the things you said should have caused the panic.

**Comment by AwlsomeAlex** [comment] 2018-09-20 17:03
Honestly I don't know what is. Nor can I get a full debug generated..... I'll keep trying.

**Comment by AwlsomeAlex** [comment] 2018-09-20 22:16
## Test Run Log 1 (No Changes):
###### 9/20/18 6:29pm
* Default Clover Install for USB (Clover_Kexts, EFIs, Patched APCI, and Custom Config)
* Installation Successful
Installer Settings:
* MOD - Fan Controls
* ACPI: SSDT-FAN-MOD.aml / SSDT-UX330-KabyLakeR.aml
* Tools Installed
* Kexts NOT Installed to /Library/Extensions
* X86PlatformPluginInjector.kext Installed
* **KERNEL PANIC WHILE KEXT CACHE REBUILDING!!! - Possibly one of the three kexts are incompatible with macOS Mojave? Got through building first one before Kernel Panic**
Note: System won't boot even with Clover from USB - Definitely problem with locally installed Kexts
### Debugging:
* Booted into Single User Mode (-s) **[No Keyboard Support - Need USB Keyboard WHILE system is booting]**
* First tried a force rebuild `sudo rm -rf /System/Library/Caches/*` and reboot
* "Okay, no kernel panic as soon as the apple logo is shown.... progress? Come on bar, go all the way! 🤞"
* "Weird, Apple Logo goes nuts (Graphical Glitching) then the loading wheel seen during shutdown shows up..... Hello?" (I'm going to assume something is VERY wrong, but my guess is the Cache is rebuilding?)
* Verbose Output: `busy timeout[0], (60s) 'AppleACPICPU'` Further research shows somethings up with HWMonitor (GPUSensors).... Interesting. 
* Booting from Internal Clover hangs on error above, booting from USB just causes a Kernel Panic, loops back to the original underlying issue. 
* Removed Three Kexts Installed to /Library/Extensions, rebuilt successfully
* Once rebooted by Rebuild, following verbose:
`AppleLMUController::getSMCProvider Error: Wait for AppleSMC provider timed out`
`AppleLMUController::start Error: Could not get SMCProvider`
`kextd stall[1], (60s) 'AppleACPICPU'` 
* Rebooted to USB, automatic Kernel Panic. :(
I'm Stuck.....

**Comment by AwlsomeAlex** [comment] 2018-09-20 22:54
## Test Run 2 (Doubted will work):
###### 9/20/18 10:00pm
* Same as Test Run 1 **EXCEPT** won't install tools (HWMonitor)
* System didn't throw a Kernel Panic while rebuilding cache [I can't confidently rule tools as problem, as I left the USB which Clover booted from plugged in. Don't know if this would affect it but....]
* However, the system won't boot from Internal Clover nor USB.
**Result: FAILURE**

## Test Run 3 (Growing suspicion):
###### 9/20/18 ?:??pm
* Same as Test Run 1 **EXCEPT** won't install x86 Injector
* Same results as Test Run 3
**Result: FAILURE**

## Test Run 4 (Unsure if will work):
###### 9/21/18 ?:??pm
* Same as Test Run 1 **EXCEPT** will use READ instead of MOD - Fan Speed
**Result: Untested**

## Test Run 5 (Definitely Work):
###### 9/21/18 ?:??pm
* Manual Install **WITHOUT** /Library/Extension Kexts (Esentially USB + X86 Injector + Fan Mods SSDT)
**Result: Untested**

Worse comes to worse, the EFI used by Clover USB can be copied to the system's EFI and **MOST** things will work, the only things lacking will be Power Management and other background things keeping the system sane.

**Comment by AwlsomeAlex** [comment] 2018-09-21 01:47
On another note, your 16 Levels work, however no Indicator like the brightness changing shows up.

**Comment by hieplpvip** [comment] 2018-09-21 02:19
That's expected behaviour

**Comment by AwlsomeAlex** [comment] 2018-09-21 02:41
Where is the X86 Injector installed? /Library/Extension or Clover?
I just can't wrap my head around what's not working. One small difference from the USB Clover and the System Clover is just not cooperating. It can't be because it's APFS right? I'd like to rule that out. I have a feeling it's either one of the SSDT Patches (Mod in particular) or one of the three kexts installed to /Library/Extension

If you know, am I at least looking in the right direction? And I'm sorry for no debugging, but it's impossible to debug something that won't even boot. I mean Single User Mode works but what can I get out of that? (Thats a genuine question, if you tell me what commands to do I can provide more details)

**Comment by hieplpvip** [comment] 2018-09-21 03:07
It must be installed to /L/E.

Send me your EFI folders from both internal drive and USB

**Comment by AwlsomeAlex** [comment] 2018-09-21 03:36
I'll try it out tomorrow some more. Also how can I extract the EFI from the System when it's in the unusable state? (I'm going to do a fresh install using the traditional ./install.sh I used for High Sierra) Should I attempt to Use F4 and F2? And to answer my question, moving the EFI from the Partition to the USB Disk using Single User Mode?

**Comment by AwlsomeAlex** [comment] 2018-09-21 23:31
Unbelievable! Installed the USB Wi-Fi Driver and automatically greeted with a Kernel Panic after reboot! 🙃 

EDIT: Might be the outdated driver that goes up to macOS El Captian (10.11).....

**Comment by AwlsomeAlex** [comment] 2018-09-21 23:56
Not sure if APFS is an issue but will use HFS+ for now in further testing. 
**SIKE!** Apple got rid of `--converttoapfs NO` >:(

**Comment by AwlsomeAlex** [comment] 2018-09-22 01:17
**HUGE DISCOVERY!!!**
Okay, so all of my experiments were bound to fail at the start! My device was accidentally rebooted, but when the system went back online, NO CHANGES WHAT-SO-EVER, the system automatically threw a kernel panic AS SOON AS THE APPLE LOGO CHANGED. What does this mean?!?

**Comment by hieplpvip** [comment] 2018-09-22 03:58
As I said, send me your EFI folder. I can do nothing without debugging files

**Comment by AwlsomeAlex** [comment] 2018-09-22 05:14
Okay. My apologies, I'll do that ASAP (Tomorrow sometime)

**Comment by AwlsomeAlex** [comment] 2018-09-25 02:29
@hieplpvip I don't understand, I can't even boot off of the USB Installer without it automatically crashing!

**Comment by AwlsomeAlex** [comment] 2018-09-25 02:32
Heres the EFI of the USB Disk. 
[EFI.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/2413552/EFI.zip)

If I recall correctly I remember this happening after a commit was made to the repository. Could a change be the problem? I don't understand why I can't even run it off of the installer.

In Verbose Mode, the last thing I can see before it crashing is
`Attempting System Recovery` or something by those lines, you have to be quick to pick it up.

**Comment by AwlsomeAlex** [comment] 2018-09-25 02:43
Got the golden ticket! 
[preboot.log.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/2413569/preboot.log.zip)
[origin.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/2413571/origin.zip)
**Finally got F2 and F4 to record something**

Graphical Issue?
`38:661  0:002  Custom boot screen not used because entry has unset use graphics`
Or the fact all the SSDT Patches shot out 
`pattern xxxxxxxx, bin not found / already patched!`
Should also note using latest Clover (Probably Mentioned) and Final Build of macOS 10.14 Mojave

**Comment by AwlsomeAlex** [comment] 2018-09-25 03:16
I hope the Preboot is sufficient to help, I don't know how to obtain any other Debugs without booting, which I can't do.

**Comment by hieplpvip** [comment] 2018-09-25 05:31
Did you use final build of Mojave to create installer?

**Comment by hieplpvip** [comment] 2018-09-25 05:33
Try removing VoodooI2C

**Comment by AwlsomeAlex** [comment] 2018-09-25 05:42
I did use Final build of Mojave (downloaded by Mojave Patcher because I’m running a Mac Pro 3,1), also is VoodooI2C using the latest update? I know one of his recent ones was prone to Kernel Panics and another one fixed it, but there is no Mojave support so I guess that doesn’t matter.

**Comment by AwlsomeAlex** [comment] 2018-09-25 05:47
No changes, still instant Kernel Panic. Also kernel panic when v2.1.1 is used. So both having it and not having it is still causing issues. 

A visual observation would be the screen kinda flickers when the Apple logo shows up then crashes without VoodooI2C, but when the VoodooI2C was updated, it just showed the loading and immediately crashed.

**Comment by hieplpvip** [comment] 2018-09-25 06:11
You should go back to High Sierra and wait, maybe a few weeks until testing is done by me.

Also, I've just done writing AsusSMC, it add native support for ALS and keyboard backlight.

If you choose to use High Sierra, I'll show you how to test AsusSMC

**Comment by hieplpvip** [comment] 2018-09-25 11:05
I've updated to Mojave, everything is working fine.

Can't get why you got kernel panic

**Comment by AwlsomeAlex** [comment] 2018-09-25 11:09
Wait, did you "Update" by System Update or Fresh Install? Also which device do you have? I really want to figure this out because there's no explanation as to why it keeps crashing. Could there be a SSDT change to my device recently which caused the whole thing to break, or a DSDT Patch which needs to be applied? The Preboot told nothing? Maybe even Clover? Could using RM's Clover be doing it?

I mean, I can barely see “Recovering System” after it loads the kext. Could the kernel be trying to load a state which doesn’t exist? Especially because even using another image macOS says there was a kernel panic. Is there a way to completely reset the system?

**Comment by hieplpvip** [comment] 2018-09-25 11:35
I updated from High Sierra, using latest RehabMan's Clover.

Boot with arguments "-v debug=0x100" and tell me what you see

**Comment by AwlsomeAlex** [comment] 2018-09-25 12:25
I’ll do that when I get home, but what I’ll do to make it a clean slate is use GParted Live CD to completely wipe the EFI partitions of both disks to make sure nothing remains, then try again with the following boot arguments.

**Comment by AwlsomeAlex** [comment] 2018-09-25 14:04
Is there a way to prevent an automatic restart and just show the Kernel panic and hang?

**Comment by hieplpvip** [comment] 2018-09-25 15:20
if "debug=0x100" doesn't work, I don't know anything else

**Comment by hieplpvip** [comment] 2018-09-25 15:58
Ok, I think I know your problem.

I've just upgraded VoodooPS2Controller, and I get an immediate kernel panic. So I revert back to previous version, and the kernel panic is gone.

Try replacing VoodooPS2Controller.kext with version 2018-0506 download from [here](https://bitbucket.org/RehabMan/os-x-voodoo-ps2-controller/downloads/)

**Comment by hieplpvip** [comment] 2018-09-25 16:00
Please try and report as soon as possible. If my guess is right, this is a serious problem

**Comment by AwlsomeAlex** [comment] 2018-09-25 17:36
I’m currently at school and won’t be home until 8pm EST (Rowing). So I’ll get back to you as soon as possible. I thought one of the recent kext updates might be contributing. Did you open a ticket with Rehabman? And is this Mojave specific or a general error?

**Comment by hieplpvip** [comment] 2018-09-25 17:47
I have open a issue, waiting for him to reply. This happens on High Sierra too

For now my script will download the old version.

I also replaced FakeSMC with VirtualSMC, replaced AsusFnKeys with AsusSMC. This provides native support for ALS and keyboard backlight. To try this you need to build the installer again (no need to erase whole USB, just replace EFI folder)

**Comment by AwlsomeAlex** [comment] 2018-09-25 19:04
That might fix that issue, but I’ve been experiencing issues with Mojave before the system would automatically crash and burn, I guess we’ll resolve this and try to move forward and actually get something running, or maybe this will fix it (hopefully).

I was reading your AsusSMC, will that require DSDT Patching or is that already incorporated with the SSDT 
Hotpatches?

I also noticed that your driver for VoodooI2C now refers to Mojave, does that fix support?

**Comment by AwlsomeAlex** [comment] 2018-09-25 23:20
Okay, so the system doesn't automatically Kernel Panic anymore. However I feel as AsusSMC has some work to be done, there is no Backlit Keyboard, No FN keys (Unless they don't work in the Installer), No Brightness (Unknown if system detects display as a laptop yet) but no Kernel Panic!

**Comment by hieplpvip** [comment] 2018-09-25 23:21
Update acpi

**Comment by AwlsomeAlex** [comment] 2018-09-25 23:22
Elaborate? Not sure how to 'Update acpi'

**Comment by hieplpvip** [comment] 2018-09-25 23:28
Did you run the scripts or install AsusSMC manually?

**Comment by AwlsomeAlex** [comment] 2018-09-25 23:31
I followed the Guide: `./download.sh && ./make_acpi.sh && ./make_config.sh` then moved the Kexts into the Other folder and moved the SSDT into the Patched Folder.

Not at that point yet. macOS Mojave is about 11 minutes left for Installation.

**Comment by hieplpvip** [comment] 2018-09-25 23:36
I think fn keys don't work in Intaller

**Comment by AwlsomeAlex** [comment] 2018-09-25 23:45
My mistake, everything is working on the welcome screen. The moment of truth, Clover Installation.

Rebooting macOS doesn't crash and burn like it used to. Better.....

install.sh: `Set: Entry, ":SMBIOS:ProductName", Does Not Exist` 
Might be useful for you, not sure.

Installation Success, No Kernel Panics.....
**404: Error Not Found :D**

Looks like everything (Except Touchpad) works now! Thank you so much!

**Comment by AwlsomeAlex** [comment] 2018-09-26 00:19
I hope to see the VoodooI2C kext updated. Any news on that?

**Comment by hieplpvip** [comment] 2018-09-26 00:21
Rebuild kextcache

**Comment by AwlsomeAlex** [comment] 2018-09-26 00:34
Yeah I'm talking to the developer right now. He doesn't have a device with Mojave yet and isn't sure why VoodooI2C doesn't work.

**Comment by hieplpvip** [comment] 2018-09-26 00:56
It's my mistake that VoodooI2C doesn't work. Will fix it as soon as possible

**Comment by AwlsomeAlex** [comment] 2018-09-26 01:15
Okay. I believe Alexandred is already taking a look as to why his driver doesn't work with Mojave. I bet you can use that for a base for why yours doesn't work.

**Comment by AwlsomeAlex** [comment] 2018-09-26 01:30
I talked to the good developers over at VoodooI2C and they said my problem is the following:
> Tell him he should add a patched _CRS for your ETPD device. It's not enough to rename it...

Don't know what this information can do for me, but its hopefully useful (and not an inconvenience for you)

**Comment by hieplpvip** [comment] 2018-09-26 01:43
The problem is I forgot to add SSDT-ELAN, which contains patch for ETPD

**Comment by hieplpvip** [comment] 2018-09-26 01:56
A fix has been pushed to the repo. Can you test it?
Just need to run:
```
cd ~/zenbook
git stash
git pull
./make_acpi.sh && ./install_acpi.sh
```

But I still don't know why you get error `Set: Entry, ":SMBIOS:ProductName", Does Not Exist`. Can you send me your EFI folder after running the above commands?

**Comment by AwlsomeAlex** [comment] 2018-09-26 02:00
Yeah, I'm debugging in two places but I would update your program to download/run VoodooI2C v2.1.2 which adds Mojave Support.

You work with ZenBooks, is it easy to replace the Wi-Fi Card? My USB Wi-Fi Dongle is not working with Mojave (Driver Issue).

**Comment by AwlsomeAlex** [comment] 2018-09-26 02:07
[EFI.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/2417759/EFI.zip)

**Comment by hieplpvip** [comment] 2018-09-26 02:34
How is it working for you?

**Comment by hieplpvip** [comment] 2018-09-26 02:47
It's very easy to replace Wifi card. Buy a DW1560, search the Internet for how to replace it.

Once you get it right, Wifi will work OOB. The kexts needed are already included

**Comment by hieplpvip** [comment] 2018-09-26 07:52
I can't boot to macOS with VoodooI2C 2.1.2. What about you?

**Comment by AwlsomeAlex** [comment] 2018-09-26 11:39
Weird, I can boot it fine, sorry I’m on EST time. Did you 1.) Include ELAN and 2.) Include the Satellite Kext? I know that’s a dumb question but I made those mistakes too. If you did (which I assume you did) I’d use the gitter for VoodooI2C and talk to Alexandred about it. Support varies at the moment. 

But is it low risk to open my UX330UAR up? There are no deconstruction guides and I don’t want to open it up to find I can’t figure out how to close it.

**Comment by hieplpvip** [comment] 2018-09-26 12:36
1. SSDT-ELAN is included now
2. The script will download the old version for safety. Did you install VoodooI2C manually, or by using the script?

**Comment by AwlsomeAlex** [comment] 2018-09-26 13:26
I installed it manually (v2.1.2) right from GitHub.

**Comment by hieplpvip** [comment] 2018-09-26 14:16
Did you update acpi before installing 2.1.2?

**Comment by AwlsomeAlex** [comment] 2018-09-26 14:18
Yes.

**Comment by hieplpvip** [comment] 2018-09-26 14:22
So how are things working, especially all and keyboard backlight?

**Comment by hieplpvip** [comment] 2018-09-26 15:09
Here a guide to disassembly UX410, should be similar to UX430: https://www.myfixguide.com/asus-zenbook-ux410uq-disassembly-and-ssd-hdd-ram-upgrade-options/

There are 10 torx (star) screws on the back + 2 cross screws under the top rubber pads.

**Comment by AwlsomeAlex** [comment] 2018-09-26 15:14
Nice, now the system won’t boot `busy timeout[0], (60s):` and it displays a bunch of ACPI patches which didn’t want to load, along with `AppleLMUController::start Error: Could not get SMCProvider`

**Comment by AwlsomeAlex** [comment] 2018-09-26 15:16
Problem with ELAN, dropping it caused system to boot.

**Comment by AwlsomeAlex** [comment] 2018-09-26 15:21
But everything else works fine and beautifully

**Comment by hieplpvip** [comment] 2018-09-26 15:37
VoodooI2C doesn't work in polling mode. When you drop SSDT-ELAN, you're switching from interrupt to polling mode. That's why it doesn't work.

Does ALS sensor work?

**Comment by AwlsomeAlex** [comment] 2018-09-26 15:39
No it wasn’t booting, it was hanging when the ELAN SSDT was loaded, it only booted because I dropped ELAN-SSDT, which gave no trackpad support.  How do I make it do that thing? 

Also not sure, but it seems like it does.

**Comment by hieplpvip** [comment] 2018-09-26 15:42
Does trackpad work when you drop SSDT-ELAN?

**Comment by hieplpvip** [comment] 2018-09-26 15:42
About keyboard backlight, do yiu have all 16 levels?

**Comment by AwlsomeAlex** [comment] 2018-09-26 15:43
I don’t recall it working since I had to use a mouse. 

Yes all 16 levels.

**Comment by hieplpvip** [comment] 2018-09-26 17:58
VoodooI2C is fixed. Can you try it?

**Comment by AwlsomeAlex** [comment] 2018-09-26 19:12
Weird, now the ELAN SSDT works...... Support seems sporadic. 

Ah I see he released an update. Will do it now.

**Comment by AwlsomeAlex** [comment] 2018-09-26 19:20
Works now. Although how do I change right click to be secondary click and drag and drop working?

**Comment by AwlsomeAlex** [comment] 2018-09-26 21:40
That's odd..... after my laptop woke up from sleep the Trackpad stopped working, along with my USB Wi-Fi Adapter. A reboot fixed it but that means somethings up with sleep.

Sleep as in closing the lid and leaving it alone from several minutes.

**Comment by AwlsomeAlex** [comment] 2018-09-27 00:00
v2.1.4 (Yet to be released) fixes this.

**Comment by hieplpvip** [comment] 2018-09-27 00:35
Can you run [gen_debug](https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/) and give me the output? Just wanna make sure everything is working properly

**Comment by AwlsomeAlex** [comment] 2018-09-27 02:34
Okay. Also if you fork VoodooI2C and make the changes for our devices we can get scaling for ZenBooks at least.

**Comment by AwlsomeAlex** [comment] 2018-09-27 02:40
[20566.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/2422265/20566.zip)

**Comment by AwlsomeAlex** [comment] 2018-09-27 02:40
Preboot might be outdated.

**Comment by AwlsomeAlex** [comment] 2018-09-27 03:13
One observation, thing heats up really quickly with fans purring with little tasks (Virtualization, but wouldn't get this bad in Windows)

**Comment by AwlsomeAlex** [comment] 2018-09-28 03:08
@hieplpvip Everything good with my system?

**Comment by hieplpvip** [comment] 2018-09-28 04:12
Sorry, I was busy fixing problem with VoodooPS2Controller.

Everything seems good

Not necessary but you may want to run `sudo nvram -c` and `./remove_backup.sh` to clean up your system

Note that keyboard backlight is now natively support. You can config it in Keyboard prefpane

**Comment by hieplpvip** [comment] 2018-09-28 04:12
Sorry, I was busy fixing problem with VoodooPS2Controller. Will check yours soon

**Comment by hieplpvip** [comment] 2018-09-28 10:35
Can you test this and report whether graphics work? Copy this to EFI/CLOVER/ACPI/patched
[SSDT-UX330-KabyLakeR.aml.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/2427833/SSDT-UX330-KabyLakeR.aml.zip)

**Comment by AwlsomeAlex** [comment] 2018-09-28 16:19
I'll test it out when I get home, since I don't want this to break on me while at school (again, lol.)

It's good to hear that the keyboard backlight is natively supported, maybe the keyboard shared by the new MacBooks are similar? Or is that because of VoodooPS2Controller.

**Comment by hieplpvip** [comment] 2018-09-29 11:32
ALS and keyboard backlight are natively supported thanks to AsusSMC, VoodooPS2Controller has nothing to do with them

**Comment by AwlsomeAlex** [comment] 2018-09-30 22:06
Okay, since I'm home I'll try the SSDT. Also can you recommend me a good Wi-Fi Card which will work with the current SSDT patches/Kexts included with the install? I'd prefer one with Handoff/AirDrop support and one which can play nicely with iMessage, since the USB I'm currently using sorta plays with iMessage but isn't reliable.

**Comment by hieplpvip** [comment] 2018-09-30 23:17
DW1560

**Comment by AwlsomeAlex** [comment] 2018-10-01 00:00
Is there anything cheaper

**Comment by hieplpvip** [comment] 2018-10-01 00:44
AFAIK, that's the best choice. I paid 22$ for it on AliExpress

**Comment by AwlsomeAlex** [comment] 2018-10-01 23:42
What about a DW1510 or DW1515 (Actually I don't know if they have Handoff Support) What about DW1550?

**Comment by hieplpvip** [comment] 2018-10-02 00:00
Why don't you buy DW1560?

**Comment by AwlsomeAlex** [comment] 2018-10-03 15:32
I live in America and am not ready to drop $60 on Amazon or $40 on eBay for a Wi-Fi Card, I'm trying to get either a ThinkPad X250 (Then Hackintosh it) or a MacBook Air 11 E2014 for school. Surprisingly are both around the same price.

**Comment by hieplpvip** [comment] 2018-10-04 00:08
Are you serious? Based on what I found on Google, ThinkPad X250 has an Intel wifi card too, and I'm pretty sure that you won't be able to get that laptop to current state of Zenbook.

**Comment by AwlsomeAlex** [comment] 2018-10-04 00:21
I decided I'm just going to get the MacBook Air 11" E2014 (Found one with 8GB) because I saw that too, while the T-series are heavily developed to work for macOS, the X-series lack greatly, except for like maybe the X220 (Which the developer stopped supporting due to Intel HD 3000 loosing support [However I got in contact with him and if I ever did acquire a X220 I'd pick up his work]) and sorta the X240 (Which isn't up to date). I guess I'll belly up for the DW1560 since I'll only be getting one instead of two (might be able to find something on eBay).

**Closed as completed** 2018-10-06 00:48 UTC
